/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'kunou' at '16/11/16 12:23' with Gradle 3.0
 *
 * @author kunou, @date 16/11/16 12:23
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
